### ISSUE TITLE
HTTP Status 500 - Resource configuration class online.JAXRSPublisher could not be loaded

### ISSUE THREAD

**Issue by Waheeb-Abdulla** [johnantonn/insight#1] opened 2016-09-11 07:44 UTC
I found this as an output:
HTTP Status 500 - Resource configuration class online.JAXRSPublisher could not be loaded

ElasticSearch 1.5.0 is runnuing
The project is imported into Eclipse
Tomcate7 is running
But when Open src/main/webapp/index.html
Right-click on index.html--->Run on server1 
Then I get:
java.lang.ClassNotFoundException: online.JAXRSPublisher
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at org.glassfish.jersey.internal.util.ReflectionHelper$7.run(ReflectionHelper.java:407)
    at org.glassfish.jersey.internal.util.ReflectionHelper$7.run(ReflectionHelper.java:397)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.glassfish.jersey.servlet.WebComponent.createResourceConfig(WebComponent.java:491)
    at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:326)
    at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:171)
    at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:363)
    at javax.servlet.GenericServlet.init(GenericServlet.java:160)
    at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1267)
    at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1186)
    at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:858)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:136)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by johnantonn** [comment] 2019-02-26 12:36
The error was reproduced, root cause was found and fixed. It had to do with the annotation of the application class and the relevant web.xml contents.

The fix was committed along with other minor changes and the code should work as expected now.

**Closed** 2019-02-26 12:36 UTC
